"""
Quick Test: Reason dengan Ollama Live
======================================
Test singkat untuk melihat hasil actual dari Ollama LLM
"""

import sys
import os
sys.path.append(os.path.join(os.path.dirname(__file__), 'backend'))

from app.services.gpt_service import predict_telecollection_outcome

# Test dengan conversation yang lebih realistic
conversation = [
    {
        "q": "Selamat siang Pak Ahmad, saya Wisnu dari ICONNET. Untuk pembayaran bulan ini sudah diselesaikan belum Pak?",
        "a": "Belum nih, maaf lupa kemarin",
        "goal": "status_contact"
    },
    {
        "q": "Tidak apa-apa Pak. Apakah ada kendala untuk pembayarannya?",
        "a": "Ga ada kendala, cuma lupa aja. Kemarin sibuk banget",
        "goal": "payment_barrier"
    },
    {
        "q": "Baik Pak, kalau begitu kapan bisa diselesaikan pembayarannya?",
        "a": "Insya Allah besok pagi saya langsung transfer",
        "goal": "payment_timeline"
    }
]

print("\n" + "="*70)
print("  QUICK TEST: OLLAMA REASON GENERATION")
print("="*70)

print("\n📝 CONVERSATION:")
for i, conv in enumerate(conversation, 1):
    print(f"\n{i}. CS: {conv['q']}")
    print(f"   Customer: {conv['a']}")

print("\n\n🔮 PREDICTING...")
result = predict_telecollection_outcome(conversation)

print(f"\n" + "="*70)
print(f"  HASIL PREDICTION")
print("="*70)
print(f"\nKeputusan: {result['keputusan']}")
print(f"Probability: {result['probability']}%")
print(f"Confidence: {result['confidence']}")
print(f"\n📄 ALASAN (Generated by Ollama):")
print("-" * 70)
print(result['alasan'])
print("-" * 70)

# Validate
if "%" in result['alasan']:
    print("\n⚠️  WARNING: Alasan masih mengandung persentase")
else:
    print("\n✅ Alasan bersih: Tidak ada persentase")

if len(result['alasan']) > 100:
    print("✅ Alasan cukup detail (>100 karakter)")
else:
    print("⚠️  Alasan terlalu pendek")

print("\n" + "="*70 + "\n")
