from app.services.gpt_service import determine_next_goal, generate_question

print("=== Test Goal-Directed System ===")

# Test 1: Conversation with financial problem
conversation = [{"q": "Ada kendala?", "a": "Ada masalah keuangan sementara"}]
goal = determine_next_goal("telecollection", conversation, {})
print(f"Next goal: {goal}")

result = generate_question("telecollection", conversation)
print(f"Question: {result.get('question')}")
print(f"Generated by: {result.get('generated_by', 'dataset')}")
print(f"Question ID: {result.get('id', 'N/A')}")

print("\n✅ Goal-directed system working!")